GO
CREATE DATABASE BDGT
GO
USE BDGT
GO
CREATE TABLE TELEFONE (
IDTel INTEGER PRIMARY KEY IDENTITY,
DDD VARCHAR(10),
Numero VARCHAR(10)
)

CREATE TABLE EMPRESA (
IDEmpresa INTEGER PRIMARY KEY IDENTITY,
RazaoSocial VARCHAR(100),
CNPJ NUMERIC(20),
IDEndereco INTEGER,
IDTel INTEGER,
IDAgenda INTEGER,
FOREIGN KEY(IDTel) REFERENCES TELEFONE (IDTel)
)

CREATE TABLE AGENDA (
IDAgenda INTEGER PRIMARY KEY IDENTITY,
Data DATETIME,
Status INTEGER,
Descricao VARCHAR(10)
)

CREATE TABLE FORNECEDOR (
IDFornecedor INTEGER PRIMARY KEY IDENTITY,
RazaoSocial VARCHAR(100),
InscricaoEstadual VARCHAR(100),
CNPJ VARCHAR(20),
Inativo INTEGER DEFAULT(0),
IDTel INTEGER,
IDEndereco INTEGER,
FOREIGN KEY(IDTel) REFERENCES TELEFONE (IDTel)
)

CREATE TABLE ENDERECO (
IDEndereco INTEGER PRIMARY KEY IDENTITY,
Numero NUMERIC(10),
Cidade VARCHAR(100),
CEP NUMERIC(20),
Estado VARCHAR(100),
Logradouro VARCHAR(100)
)

CREATE TABLE PRODUTO (
Inativo INTEGER DEFAULT(0),
IDProduto INTEGER PRIMARY KEY IDENTITY,
Titulo VARCHAR(100),
Intensidade DECIMAL(18,2),
Cor VARCHAR(10),
Metragem DECIMAL(18,2),
ValorMetro DECIMAL(18,2),
Estoque INTEGER
)

CREATE TABLE USUARIO (
IDUsuario INTEGER PRIMARY KEY IDENTITY,
Email VARCHAR(100),
Nome VARCHAR(100),
Inativo INTEGER DEFAULT(0),
CPF NUMERIC(13),
IDEndereco INTEGER,
IDTel INTEGER,
FOREIGN KEY(IDEndereco) REFERENCES ENDERECO (IDEndereco),
FOREIGN KEY(IDTel) REFERENCES TELEFONE (IDTel)
)

CREATE TABLE ORDEMSERVICO (
IDOrdemservico INTEGER PRIMARY KEY IDENTITY,
Desconto DECIMAL(18,2),
Data DATETIME,
Status INTEGER,
Inativo INTEGER DEFAULT(0),
ValorVenda DECIMAL(18,2),
IDEmpresa INTEGER,
FOREIGN KEY(IDEmpresa) REFERENCES EMPRESA (IDEmpresa)
)

CREATE TABLE PROMOCAO (
Titulo VARCHAR(100),
Descricao VARCHAR(100),
Inativo INTEGER DEFAULT(0),
IDPromocao INTEGER PRIMARY KEY IDENTITY,
ValorDesconto DECIMAL(18,2)
)

select * from ORDEMSERVICO

CREATE TABLE ORDEMITEM (
IDProduto INTEGER,
IDOrdemservico INTEGER,
IDOrdemItem INTEGER PRIMARY KEY IDENTITY,
ValorMetro DECIMAL(18,2),
Metragem DECIMAL(18,2),
FOREIGN KEY(IDProduto) REFERENCES PRODUTO (IDProduto),
FOREIGN KEY(IDOrdemservico) REFERENCES ORDEMSERVICO (IDOrdemservico)
)

CREATE TABLE PROMITEM (
IDPromocao INTEGER,
IDUsuario INTEGER,
Valor DECIMAL(18,2),
Quantidade INTEGER,
IDPromItem INTEGER PRIMARY KEY IDENTITY,
FOREIGN KEY(IDPromocao) REFERENCES PROMOCAO (IDPromocao),
FOREIGN KEY(IDUsuario) REFERENCES USUARIO (IDUsuario)
)
GO
ALTER TABLE EMPRESA ADD FOREIGN KEY(IDEndereco) REFERENCES ENDERECO (IDEndereco)
ALTER TABLE EMPRESA ADD FOREIGN KEY(IDAgenda) REFERENCES AGENDA (IDAgenda)
ALTER TABLE FORNECEDOR ADD FOREIGN KEY(IDEndereco) REFERENCES ENDERECO (IDEndereco)

GO
--================================================================= AGENDA =======================================================================
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoAGENDA]
	@ACAO INT,
	@IDAgenda INT,
	@DATA DATETIME,
	@STATUS INT,
	@DESCRICAO VARCHAR(10)

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO AGENDA(Data, Descricao) 
				VALUES (@Data, @Descricao)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE AGENDA SET Data = @DATA, Descricao = @DESCRICAO
				WHERE IDAgenda = @IDAgenda

			ELSE IF(@ACAO = 3)
				DELETE AGENDA WHERE IDAGENDA = @IDAGENDA

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

GO	
	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarAGENDA]
	@ACAO		INT,
	@IDAgenda	INT,
	@DESCRICAO VARCHAR(150)
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM AGENDA WHERE IDAgenda = @IDAgenda ORDER BY IDAgenda

			ELSE IF(@ACAO = 2)
				SELECT * FROM AGENDA WHERE DESCRICAO LIKE @DESCRICAO + '%' ORDER BY DESCRICAO

			ELSE
				SELECT * FROM AGENDA ORDER BY IDAgenda
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

--=========================================================== EMPRESA =========================================================================
GO
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoEMPRESA]
	@ACAO INT,
	@IDEMPRESA		INT,
	@RAZAOSOCIAL	VARCHAR(100),
	@CNPJ			NUMERIC(20,0),
	@IDENDERECO		INT,
	@IDTEL			INT,
	@IDAGENDA		INT

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO EMPRESA(RazaoSocial, CNPJ, IDEndereco, IDTel, IDAgenda) 
				VALUES (@RazaoSocial, @CNPJ, @IDEndereco, @IDTel, @IDAgenda)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE EMPRESA SET RazaoSocial = @RAZAOSOCIAL, CNPJ = @CNPJ, IDEndereco = @IDENDERECO, IDTel = @IDTEL, IDAgenda = @IDAGENDA
				WHERE IDEMPRESA = @IDEMPRESA

			ELSE IF(@ACAO = 3)
				DELETE EMPRESA WHERE IDEMPRESA = @IDEMPRESA

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

GO	
	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarEMPRESA]
	@ACAO		INT,
	@IDEMPRESA	INT,
	@RAZAOSOCIAL VARCHAR(100)
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM EMPRESA WHERE IDEMPRESA = @IDEMPRESA ORDER BY IDEMPRESA

			ELSE IF(@ACAO = 2)
				SELECT * FROM EMPRESA WHERE RAZAOSOCIAL LIKE @RAZAOSOCIAL + '%' ORDER BY RAZAOSOCIAL

			ELSE
				SELECT * FROM EMPRESA ORDER BY IDEMPRESA
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

--==================================================================== ENDERECO ===================================================================
GO
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoENDERECO]
	@ACAO INT,
	@IDENDERECO INT,
	@NUMERO		NUMERIC(10,0),
	@CIDADE		VARCHAR(100),
	@CEP		NUMERIC(20,0),
	@ESTADO		VARCHAR(100),
	@LOGRADOURO VARCHAR(100)

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO ENDERECO(Numero, Cidade, CEP, Estado, Logradouro) 
				VALUES (@Numero, @Cidade, @CEP, @Estado, @Logradouro)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE ENDERECO SET Numero = @NUMERO, Cidade = @CIDADE, CEP = @CEP, Estado = @ESTADO, Logradouro = @LOGRADOURO
				WHERE IDENDERECO = @IDENDERECO

			ELSE IF(@ACAO = 3)
				DELETE ENDERECO WHERE IDENDERECO = @IDENDERECO

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

	
GO	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarENDERECO]
	@ACAO		INT,
	@IDENDERECO INT,
	@LOGRADOURO VARCHAR(100)
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM ENDERECO WHERE IDENDERECO = @IDENDERECO ORDER BY IDENDERECO

			ELSE IF(@ACAO = 2)
				SELECT * FROM ENDERECO WHERE LOGRADOURO LIKE @LOGRADOURO + '%' ORDER BY LOGRADOURO

			ELSE
				SELECT * FROM ENDERECO ORDER BY IDENDERECO
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

--============================================================================= FORNECEDOR ========================================================
GO
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoFORNECEDOR]
	@ACAO INT,
	@IDFORNECEDOR INT,
	@RAZAOSOCIAL VARCHAR(100),
	@INSCRICAOESTADUAL VARCHAR(100),
	@CNPJ VARCHAR(20),
	@INATIVO INT,
	@IDTEL INT,
	@IDENDERECO INT

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO FORNECEDOR(RazaoSocial, InscricaoEstadual, CNPJ, Inativo, IDTel, IDEndereco) 
				VALUES (@RazaoSocial, @InscricaoEstadual, @CNPJ, @Inativo, @IDTel, @IDEndereco)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE FORNECEDOR SET RazaoSocial = @RAZAOSOCIAL, InscricaoEstadual = @INSCRICAOESTADUAL, 
				CNPJ = @CNPJ, Inativo = Inativo, IDTel = IDTel, IDEndereco = @IDENDERECO
				WHERE IDFORNECEDOR = @IDFORNECEDOR

			ELSE IF(@ACAO = 3)
				DELETE FORNECEDOR WHERE IDFORNECEDOR = @IDFORNECEDOR

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

GO	
	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarFORNECEDOR]
	@ACAO INT,
	@IDFORNECEDOR INT,
	@RAZAOSOCIAL VARCHAR(100)
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM FORNECEDOR WHERE IDFORNECEDOR = @IDFORNECEDOR AND INATIVO = 0 ORDER BY IDFORNECEDOR

			ELSE IF(@ACAO = 2)
				SELECT * FROM FORNECEDOR WHERE RAZAOSOCIAL LIKE @RAZAOSOCIAL + '%' AND INATIVO = 0 ORDER BY RAZAOSOCIAL

			ELSE
				SELECT * FROM FORNECEDOR WHERE INATIVO = 0 ORDER BY IDFORNECEDOR
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH


GO
--==================================================================== ORDEM ITEM ======================================================================
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoORDEMITEM]
	@ACAO INT,
	@IDOrdemItem	INT,
	@ValorMetro		DECIMAL(18,2),
	@METRAGEM		DECIMAL(18,2),
	@IDPRODUTO		INT,
	@IDORDEMSERVICO INT

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO ORDEMITEM(ValorMetro, Metragem, IDProduto, IDOrdemservico) 
				VALUES (@ValorMetro, @Metragem, @IDProduto, @IDOrdemservico)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE ORDEMITEM SET ValorMetro = @ValorMetro, Metragem = @METRAGEM, IDProduto = @IDPRODUTO, IDOrdemservico = @IDORDEMSERVICO
				WHERE IDOrdemItem = @IDOrdemItem

			ELSE IF(@ACAO = 3)
				DELETE ORDEMITEM WHERE IDOrdemItem = @IDOrdemItem

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

	
	GO
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarORDEMITEM]
	@ACAO			INT,
	@IDOrdemItem	INT,
	@IDOrdemServico INT,
	@IDPRODUTO INT 
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM ORDEMITEM WHERE IDOrdemItem = @IDOrdemItem ORDER BY IDOrdemItem

			ELSE IF(@ACAO = 2)
				SELECT O.*, P.Titulo AS TITULO FROM ORDEMITEM AS O JOIN PRODUTO AS P 
				ON O.IDOrdemservico = @IDOrdemServico AND O.IDProduto = P.IDProduto ORDER BY IDOrdemItem

			ELSE IF(@ACAO = 3)
				SELECT * FROM ORDEMITEM WHERE IDOrdemservico = @IDOrdemServico AND IDProduto = @IDPRODUTO  ORDER BY IDOrdemItem

			ELSE IF(@ACAO = 4)
				SELECT O.*, P.Titulo AS TITULO FROM ORDEMITEM AS O JOIN PRODUTO AS P 
				ON O.IDProduto = @IDPRODUTO AND O.IDProduto = P.IDProduto ORDER BY IDOrdemItem

			ELSE
				SELECT * FROM ORDEMITEM ORDER BY IDOrdemItem
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH
GO
--==================================================================== ORDEM SERVIÇO ======================================================================
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoORDEMSERVICO]
	@ACAO INT,
	@IDORDEMSERVICO INT,
	@DATA DATETIME,
	@STATUS INT,
	@VALORVENDA DECIMAL(18,2),
	@IDEMPRESA INT

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO ORDEMSERVICO(Status, IDEmpresa) 
				VALUES (@Status, @IDEmpresa)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE ORDEMSERVICO SET Data = @DATA, Status = @STATUS, ValorVenda = @VALORVENDA, IDEmpresa = @IDEMPRESA
				WHERE IDORDEMSERVICO = @IDORDEMSERVICO

			ELSE IF(@ACAO = 3)
				DELETE ORDEMSERVICO WHERE IDORDEMSERVICO = @IDORDEMSERVICO

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

GO	
	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarORDEMSERVICO]
	@ACAO INT,
	@IDORDEMSERVICO INT,
	@IDEMPRESA INT,
	@DATAINICIO DATETIME,
	@DATAFINAL DATETIME
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM ORDEMSERVICO WHERE IDORDEMSERVICO = @IDORDEMSERVICO AND Inativo = 0 ORDER BY IDORDEMSERVICO

			ELSE IF(@ACAO = 2)
				SELECT * FROM ORDEMSERVICO WHERE IDEMPRESA = @IDEMPRESA AND Inativo = 0 ORDER BY IDORDEMSERVICO

			ELSE IF(@ACAO = 3)
				SELECT * FROM ORDEMSERVICO WHERE Status = 0 AND Inativo = 0 ORDER BY IDORDEMSERVICO

			ELSE IF(@ACAO = 4)
				SELECT MAX(IDOrdemservico) FROM ORDEMSERVICO WHERE Inativo = 0

			ELSE IF(@ACAO = 5)
				SELECT O.*, A.RazaoSocial AS NOME FROM ORDEMSERVICO AS O JOIN EMPRESA AS A  
				ON O.Data BETWEEN @DATAINICIO AND @DATAFINAL AND O.Inativo = 0
				AND O.IDEmpresa = A.IDEmpresa

			ELSE
				SELECT * FROM ORDEMSERVICO WHERE Inativo = 0 ORDER BY IDORDEMSERVICO
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH
GO
--==================================================================== PRODUTO ======================================================================
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoPRODUTO]
	@ACAO INT,
	@IDPRODUTO INT,
	@TITULO VARCHAR(100),
	@INTENSIDADE DECIMAL(18,2),
	@COR VARCHAR(10),
	@METRAGEM DECIMAL(18,2),
	@VALORMETRO DECIMAL(18,2),
	@ESTOQUE INT

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO PRODUTO(Titulo, Intensidade, Cor, Metragem, ValorMetro, Estoque) 
				VALUES (@Titulo, @Intensidade, @Cor, @Metragem, @ValorMetro, @Estoque)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE PRODUTO SET Titulo = @TITULO, Intensidade = @INTENSIDADE, Cor = Cor, 
				Metragem = @METRAGEM, ValorMetro = @VALORMETRO, Estoque = @ESTOQUE
				WHERE IDPRODUTO = @IDPRODUTO

			ELSE IF(@ACAO = 3)
				DELETE PRODUTO WHERE IDPRODUTO = @IDPRODUTO

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

GO	
	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarPRODUTO]
	@ACAO INT,
	@IDPRODUTO INT,
	@TITULO VARCHAR(100)
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM PRODUTO WHERE IDPRODUTO = @IDPRODUTO AND Inativo = 0 ORDER BY IDPRODUTO

			ELSE IF(@ACAO = 2)
				SELECT * FROM PRODUTO WHERE Titulo LIKE @TITULO + '%' AND Inativo = 0 ORDER BY Titulo

			ELSE
				SELECT * FROM PRODUTO WHERE Inativo = 0 ORDER BY IDPRODUTO
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH
GO
--==================================================================== PROMOÇÃO ITEM ======================================================================
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoPROMITEM]
	@ACAO INT,
	@IDPROMITEM INT,
	@IDPROMOCAO INT,
	@IDUSUARIO INT,
	@VALOR DECIMAL(18,2),
	@QUANTIDADE INT

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO PROMITEM(IDPromocao, Valor, Quantidade) 
				VALUES (@IDPromocao, @Valor, @Quantidade)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE PROMITEM SET IDPromocao = @IDPROMOCAO, Valor = @VALOR, Quantidade = @QUANTIDADE
				WHERE IDPROMITEM = @IDPROMITEM

			ELSE IF(@ACAO = 3)
				DELETE PROMITEM WHERE IDPROMITEM = @IDPROMITEM

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

GO	
	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarPROMITEM]
	@ACAO INT,
	@IDPROMITEM INT,
	@IDPROMOCAO INT,
	@IDUSUARIO INT
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM PROMITEM WHERE IDPROMITEM = @IDPROMITEM ORDER BY IDPROMITEM

			ELSE IF(@ACAO = 2)
				SELECT * FROM PROMITEM WHERE IDPROMOCAO = @IDPROMOCAO ORDER BY IDPROMITEM

			ELSE IF(@ACAO = 3)
				SELECT * FROM PROMITEM WHERE IDUSUARIO = @IDUSUARIO ORDER BY IDPROMITEM

			ELSE
				SELECT * FROM PROMITEM ORDER BY IDPROMITEM
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH
GO
--==================================================================== PROMOCAO ======================================================================
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoPROMOCAO]
	@ACAO INT,
	@IDPROMOCAO INT,
	@TITULO VARCHAR(100),
	@DESCRICAO VARCHAR(100),
	@VALORDESCONTO DECIMAL(18,2)

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO PROMOCAO(Titulo, Descricao, ValorDesconto) 
				VALUES (@Titulo, @Descricao, @ValorDesconto)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE PROMOCAO SET Titulo = @TITULO, Descricao = @DESCRICAO, 
				ValorDesconto = @VALORDESCONTO
				WHERE IDPROMOCAO = @IDPROMOCAO

			ELSE IF(@ACAO = 3)
				DELETE PROMOCAO WHERE IDPROMOCAO = @IDPROMOCAO

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

GO	
	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarPROMOCAO]
	@ACAO INT,
	@IDPROMOCAO INT,
	@DESCRICAO VARCHAR(150),
	@TITULO VARCHAR(100)
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM PROMOCAO WHERE IDPROMOCAO = @IDPROMOCAO AND Inativo = 0 ORDER BY IDPROMOCAO

			ELSE IF(@ACAO = 2)
				SELECT * FROM PROMOCAO WHERE DESCRICAO LIKE @DESCRICAO + '%' AND Inativo = 0 ORDER BY DESCRICAO

			ELSE IF(@ACAO = 3)
				SELECT * FROM PROMOCAO WHERE TITULO LIKE @TITULO + '%' AND Inativo = 0 ORDER BY Titulo

			ELSE
				SELECT * FROM PROMOCAO WHERE Inativo = 0 ORDER BY IDPROMOCAO
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH
GO
--==================================================================== TELEFONE ======================================================================
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoTELEFONE]
	@ACAO	INT,
	@IDTEL	INT,
	@DDD	VARCHAR(10),
	@NUMERO VARCHAR(10)

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO TELEFONE(DDD, Numero) 
				VALUES (@DDD, @Numero)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE TELEFONE SET DDD = @DDD, Numero = @NUMERO
				WHERE IDTEL = @IDTEL

			ELSE IF(@ACAO = 3)
				DELETE TELEFONE WHERE IDTEL = @IDTEL

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

GO	
	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarTELEFONE]
	@ACAO	INT,
	@IDTEL	INT,
	@NUMERO VARCHAR(150)
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM TELEFONE WHERE IDTEL = @IDTEL ORDER BY IDTEL

			ELSE IF(@ACAO = 2)
				SELECT * FROM TELEFONE WHERE NUMERO LIKE @NUMERO + '%' ORDER BY NUMERO

			ELSE
				SELECT * FROM TELEFONE ORDER BY IDTEL
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH
GO
--==================================================================== USUARIO ======================================================================
CREATE OR ALTER PROCEDURE [dbo].[uspAcaoUSUARIO]
	@ACAO INT,
	@IDUSUARIO INT,
	@EMAIL VARCHAR(100),
	@NOME VARCHAR(100),
	@CPF NUMERIC(13,0),
	@IDENDERECO INT,
	@IDTEL INT

AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
			BEGIN
				INSERT INTO USUARIO(Email, Nome, CPF, IDEndereco, IDTel) 
				VALUES (@Email, @Nome, @CPF, @IDEndereco, @IDTel)
				SELECT @@IDENTITY
			END

			ELSE IF(@ACAO = 2)
				UPDATE USUARIO SET Email = @EMAIL, Nome = @NOME, CPF = @CPF, IDEndereco = @IDENDERECO, IDTel = @IDTEL
				WHERE IDUSUARIO = @IDUSUARIO

			ELSE IF(@ACAO = 3)
				DELETE USUARIO WHERE IDUSUARIO = @IDUSUARIO

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH

	
GO	
CREATE OR ALTER PROCEDURE [dbo].[uspPesquisarUSUARIO]
	@ACAO INT,
	@IDUSUARIO INT,
	@NOME VARCHAR(100)
AS
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRAN

			IF(@ACAO = 1)
				SELECT * FROM USUARIO WHERE IDUSUARIO = @IDUSUARIO AND INATIVO = 0 ORDER BY IDUSUARIO

			ELSE IF(@ACAO = 2)
				SELECT * FROM USUARIO WHERE NOME LIKE @NOME + '%' AND INATIVO = 0 ORDER BY NOME

			ELSE
				SELECT * FROM USUARIO WHERE INATIVO = 0 ORDER BY IDUSUARIO
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRAN
	END CATCH